# -*- coding: utf-8 -*-
"""Ecocnomía Circular.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TLsH40EaVazpxNndR8h2ugCyffLoDXsZ
"""

# app.py
# ---------------------------------------------------------
# MiPyME Conecta - Asignación Eficiente de Crédito
# Economía Circular + Polos de Desarrollo + Random Forest
# Versión optimizada para pitch (ULTRA RÁPIDA)
# Con Login de Usuario
# ---------------------------------------------------------

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import plotly.express as px

# ---------------------------------------------------------
# CONFIGURACIÓN GENERAL
# ---------------------------------------------------------
st.set_page_config(layout="wide", page_title="Asignación Inteligente de Crédito MiPyME")

# ---------------------------------------------------------
# LOGIN SIMPLE (USUARIO Y CLAVE)
# ---------------------------------------------------------
USUARIOS = {
    "admin": "1234",
    "pitch": "demo2025",
    "invitado": "credito"
}

def login():
    st.title("🔐 Acceso a MiPyME Conecta")
    usuario = st.text_input("Usuario")
    clave = st.text_input("Contra_