# -*- coding: utf-8 -*-
"""Ecocnomía Circular.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TLsH40EaVazpxNndR8h2ugCyffLoDXsZ
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

st.set_page_config(page_title="Crédito Inteligente MiPyME", layout="wide")

st.title("💳 Asignación Inteligente de Crédito para MiPyMEs")
st.success("Demo en tiempo real — IA para economía circular, polos de desarrollo y género")

st.markdown("""
Este prototipo prioriza MiPyMEs con:
- 🌱 Economía circular
- 📍 Polos de desarrollo
- 👩 Liderazgo femenino
- 💻 Digitalización
""")

# -----------------------------
# DATOS SINTÉTICOS MUY RÁPIDOS
# -----------------------------
@st.cache_data
def generar_datos(n=600):
    np.random.seed(42)
    estados = ['CDMX','Jalisco','NL','Puebla','Oaxaca','Veracruz']

    df = pd.DataFrame({
        "estado": np.random.choice(estados, n),
        "ventas": np.random.randint(200_000, 5_000_000, n),
        "empleados": np.random.randint(1, 50, n),
        "recicla": np.random.rand(n),
        "digital": np.random.rand(n),
        "mujer": np.random.binomial(1, 0.35, n)
    })

    # MODELO INTELIGENTE SIMULADO (ultra rápido)
    score = (
        0.35 * df["digital"] +
        0.30 * df["recicla"] +
        0.20 * df["mujer"] +
        0.15 * np.log1p(df["ventas"])
    )

    df["credito"] = (score > score.quantile(0.7)).astype(int)
    df["score"] = score
    return df

df = generar_datos()

# -----------------------------
# KPI PRINCIPALES
# -----------------------------
col1, col2, col3 = st.columns(3)

col1.metric("MiPyMEs con crédito", f"{df['credito'].mean()*100:.1f}%")
col2.metric("Empresas evaluadas", f"{len(df)}")
col3.metric("Score promedio IA", f"{df['score'].mean():.3f}")

# -----------------------------
# POLOS DE DESARROLLO (RÁPIDO)
# -----------------------------
st.subheader("📍 Polos de Desarrollo")

polos = df.groupby("estado").agg(
    empresas=("ventas","count"),
    credito=("credito","mean"),
    score=("score","mean")
).reset_index()

fig = px.scatter(
    polos,
    x="empresas",
    y="score",
    size="empresas",
    color="credito",
    hover_name="estado",
    title="Estados Prioritarios para Crédito"
)

st.plotly_chart(fig, use_container_width=True)

# -----------------------------
# EVALUADOR DE CRÉDITO EN VIVO
# -----------------------------
st.subheader("✅ Evaluación Inteligente de una MiPyME")

with st.form("eval"):
    ventas = st.number_input("Ventas anuales (MXN)", 100000, 10_000_000, 1_000_000)
    empleados = st.number_input("Empleados", 1, 100, 8)
    recicla = st.slider("Nivel de economía circular", 0.0, 1.0, 0.3)
    digital = st.slider("Nivel de digitalización", 0.0, 1.0, 0.4)
    mujer = st.selectbox("¿Liderazgo femenino?", [0,1])

    evaluar = st.form_submit_button("Evaluar crédito")

    if evaluar:
        score = (
            0.35 * digital +
            0.30 * recicla +
            0.20 * mujer +
            0.15 * np.log1p(ventas)
        )

        prob = min(score, 1)

        if prob > 0.6:
            st.success(f"✅ Crédito aprobado con probabilidad estimada de {prob:.1%}")
        else:
            st.warning(f"⚠️ Riesgo crediticio — Probabilidad estimada: {prob:.1%}")

# -----------------------------
# SIMULADOR DE POLÍTICA PÚBLICA
# -----------------------------
st.subheader("📈 Simulador de Impacto en Crédito")

cap = st.slider("Cobertura de capacitación digital (%)", 0, 50, 10)
impacto = cap * 0.002

actual = df["credito"].mean()
nuevo = actual + impacto

st.write(f"Acceso actual: {actual:.2%}")
st.write(f"Acceso proyectado: {nuevo:.2%}")

if nuevo - actual >= 0.035:
    st.success("✅ Se cumple la meta anual de +3.5%")
else:
    st.warning("⚠️ No se alcanza aún la meta del +3.5%")

st.caption("Prototipo optimizado para pitch: IA ligera, decisiones en tiempo real, sin tiempos muertos.")